export const PERMISSIONS = {
  // Contact
  CONTACT_VIEW: 'CONTACT_VIEW',
  CONTACT_CREATE: 'CONTACT_CREATE',
  CONTACT_EDIT: 'CONTACT_EDIT',
  CONTACT_DELETE: 'CONTACT_DELETE',

  // Hotel
  HOTEL_VIEW: 'HOTEL_VIEW',
  HOTEL_CREATE: 'HOTEL_CREATE',
  HOTEL_EDIT: 'HOTEL_EDIT',
  HOTEL_DELETE: 'HOTEL_DELETE',

  // Department
  DEPARTMENT_VIEW: 'DEPARTMENT_VIEW',
  DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
  DEPARTMENT_EDIT: 'DEPARTMENT_EDIT',
  DEPARTMENT_DELETE: 'DEPARTMENT_DELETE',

  // User
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_EDIT: 'USER_EDIT',
  USER_DELETE: 'USER_DELETE',

  // Role
  ROLE_MANAGE: 'ROLE_MANAGE',  //هنشيلها 
// Role
ROLE_VIEW: 'ROLE_VIEW',
ROLE_CREATE: 'ROLE_CREATE',
ROLE_EDIT: 'ROLE_EDIT',
ROLE_DELETE: 'ROLE_DELETE',
ROLE_ASSIGN_PERMISSIONS: 'ROLE_ASSIGN_PERMISSIONS',

  // Log
  LOG_VIEW: 'LOG_VIEW',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
